import img from "@/public/frame1.png";
import img2 from "@/public/frame2.png";
import img3 from "@/public/3.png";
import img4 from "@/public/4.png";
const FastProduct = [
  {
    id: 1,
    href: "/",
    discount: "40%",
    img: img, // Görsel yolunu doğru şekilde belirtin
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 5,
    reviews: 88,
  },
  {
    id: 2,
    href: "/",
    discount: "40%",
    img: img2,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 3,
    href: "/",
    discount: "40%",
    img: img3,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 4,
    href: "/",
    discount: "40%",
    img: img4,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 5,
    href: "/",
    discount: "40%",
    img: img4,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 6,
    href: "/",
    discount: "40%",
    img: img2,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 7,
    href: "/",
    discount: "40%",
    img: img3,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 8,
    href: "/",
    discount: "40%",
    img: img4,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
  {
    id: 9,
    href: "/",
    discount: "40%",
    img: img4,
    name: "HAVIT HV-G92 Gamepad",
    price: 120,
    oldPrice: 160,
    rating: 4.5,
    reviews: 75,
  },
];


export default FastProduct;
